# Generated by Django 4.1.3 on 2022-12-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_register_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_model',
            old_name='User_id',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='register_model',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
