# Generated by Django 4.1.3 on 2022-12-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_rename_user_id_register_model_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_model',
            name='forget_token',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
