# Generated by Django 4.1.3 on 2022-12-12 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_register_model_forget_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_model',
            name='forget_token',
        ),
    ]
